---
title: "china _ diabetic"
author: "Daniel"
date: "2023-10-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=F, echo=F, eval=F}
if(!require(pacman)) install.packages("pacman")   
 pacman::p_load( tidyverse,rio,knit)   
```

```{r message=FALSE}
diab_china_dat_raw <- import("https://docs.google.com/uc?id=1NKOf-O-6MmB--zloZnyNfAo4uL2NI1uA&export=download",
                            format = "csv",
                           setclass = "tibble") 
diab_china_dat_raw

```

```{r}
diab_china_dat_raw %>% select(weight_kg,height_cm)
```
```{r}
diab_china_dat_raw %>% select(sbp_mm_hg:ccr_umol_l)
```
```{r}
diab_china_dat_raw %>% select(-family_history_of_diabetes)
```
```{r}
diab_china_dat_raw %>% select(!family_history_of_diabetes)
```

```{r}
diab_china_dat_raw %>% select(contains("status"))
```
```{r}
diab_china_dat <- diab_china_dat_raw %>% select(fpg_of_final_visit_mmol_l,everything())
diab_china_dat
```

```{r}
diab_china_dat <- diab_china_dat_raw %>% rename(followup_year = year_of_followup)
diab_china_dat
```




































